[package]
name = "commonware-collector-demo"
edition.workspace = true
publish = true
version.workspace = true
license.workspace = true
description = "Demonstrate collecting responses from multiple nodes using commonware-collector."
readme = "README.md"
homepage.workspace = true
repository = "https://github.com/commonwarexyz/monorepo/tree/main/examples/collector-demo"
documentation = "https://docs.rs/commonware-collector-demo"

[dependencies]
bytes.workspace = true
clap.workspace = true
commonware-codec.workspace = true
commonware-collector.workspace = true
commonware-cryptography.workspace = true
commonware-macros.workspace = true
commonware-p2p.workspace = true
commonware-runtime.workspace = true
commonware-utils.workspace = true
async-lock.workspace = true
futures.workspace = true
governor.workspace = true
prometheus-client.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[[bin]]
name = "commonware-collector-demo"
bench = false
