[package]
name = "commonware-vrf"
edition.workspace = true
publish = true
version.workspace = true
license.workspace = true
description = "Generate bias-resistant randomness with untrusted contributors using commonware-cryptography and commonware-p2p."
readme = "README.md"
homepage.workspace = true
repository = "https://github.com/commonwarexyz/monorepo/tree/main/examples/vrf"
documentation = "https://docs.rs/commonware-vrf"

[dependencies]
commonware-codec = { workspace = true }
commonware-cryptography = { workspace = true }
commonware-macros = { workspace = true }
commonware-p2p = { workspace = true }
commonware-runtime = { workspace = true }
commonware-utils = { workspace = true }
bytes = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
clap = { workspace = true }
tracing-subscriber = { workspace = true }
prometheus-client = { workspace = true }
governor = { workspace = true }

[dev-dependencies]
rand_chacha = { workspace = true }

[[bin]]
name = "commonware-vrf"
bench = false
