[package]
name = "commonware-vrf"
edition = "2021"
publish = true
version = "0.0.5"
license = "MIT OR Apache-2.0"
description = "Generate bias-resistant randomness with untrusted contributors using commonware-cryptography and commonware-p2p."
readme = "README.md"
homepage = "https://commonware.xyz"
repository = "https://github.com/commonwarexyz/monorepo/tree/main/examples/vrf"
documentation = "https://docs.rs/commonware-vrf"

[dependencies]
commonware-cryptography = { workspace = true }
commonware-p2p = { workspace = true } 
commonware-runtime = { workspace = true }
bytes = { workspace = true } 
rand = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true } 
prost = { workspace = true } 
clap = "4" 
tracing-subscriber = "0.3"
prometheus-client = "0.22"
governor = "0.6"

[build-dependencies]
prost-build = { workspace = true } 