[test-groups]
slow = { max-threads = "num-cpus" }
conformance = { max-threads = "num-cpus" }

[profile.default]
default-filter = 'not test(/(.*_slow_$|.*_conformance_$)/)'

[profile.slow]
default-filter = 'test(/.*_slow_$/)'

[profile.conformance]
default-filter = 'test(/.*_conformance_$/)'

[profile.all]
default-filter = 'test(/.*/)'
