[package]
name = "commonware-parallel"
edition.workspace = true
publish = true
version.workspace = true
license.workspace = true
description = "Abstract data parallelism over iterators and tasks."
readme = "README.md"
homepage.workspace = true
repository = "https://github.com/commonwarexyz/monorepo/tree/main/parallel"

[lints]
workspace = true

[dependencies]
cfg-if.workspace = true
rayon = { workspace = true, optional = true }

[dev-dependencies]
proptest.workspace = true

[features]
default = [ "std" ]
std = [ "dep:rayon" ]
