[package]
name = "commonware-math"
edition.workspace = true
publish = true
version.workspace = true
license.workspace = true
description = "Mathematical utilities and operations."
readme = "README.md"
homepage.workspace = true
repository = "https://github.com/commonwarexyz/monorepo/tree/main/math"
documentation = "https://docs.rs/commonware-math"

[features]
default = [ "std" ]
test_strategies = [ "dep:proptest" ]
std = [
	"bytes/std",
	"commonware-codec/std",
	"commonware-utils/std",
	"rand_core/std",
]

[dependencies]
bytes.workspace = true
commonware-codec.workspace = true
commonware-utils.workspace = true
proptest = { workspace = true, optional = true }
rand_core.workspace = true

[dev-dependencies]
proptest.workspace = true
rand.workspace = true
rand_chacha.workspace = true

[lib]
bench = false
