[package]
name = "commonware-p2p"
edition = "2021"
publish = true
version = "0.0.13"
license = "MIT OR Apache-2.0"
description = "Communicate with authenticated peers over encrypted connections."
readme = "README.md"
homepage = "https://commonware.xyz"
repository = "https://github.com/commonwarexyz/monorepo"
documentation = "https://docs.rs/commonware-p2p"

[dependencies]
commonware-cryptography = { workspace = true }
bytes = { workspace = true } 
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
futures = "0.3"
governor = "0.6"
x25519-dalek = { version = "2", features = ["getrandom"] }
chacha20poly1305 = "0.10"
prost = "0.12"
sha2 = "0.10"
hex = "0.4"
tracing = "0.1"
bitvec = "1"
prometheus-client = "0.22"
rand = "0.8"

[dev-dependencies]
tokio-test = "0.4"

[build-dependencies]
prost-build = "0.12"