["commonware_p2p::authenticated::data::tests::conformance::CodecConformance<Data>"]
n_cases = 65536
hash = "9ac108602dd289884580649d0362ab6b291fc8b9afbe9085ad98e61087f8263e"

["commonware_p2p::authenticated::discovery::types::tests::conformance::CodecConformance<BitVec>"]
n_cases = 65536
hash = "6e3772525660cd57a4223330b548ab47656d68ab0bfb8014d4efbeb9c1646508"

["commonware_p2p::authenticated::discovery::types::tests::conformance::CodecConformance<Info<PublicKey>>"]
n_cases = 65536
hash = "7c1646839909a5ae140c9f4bcc6d6ce8e5322ecf32836a2cfa8122b0399eaf50"

["commonware_p2p::authenticated::discovery::types::tests::conformance::CodecConformance<Payload<PublicKey>>"]
n_cases = 65536
hash = "bb07d69b33a1ed8c6db99aad2104f7c5cada6767fe5a373ebfe9f0d42c1c85b3"

["commonware_p2p::authenticated::lookup::types::tests::conformance::CodecConformance<Message>"]
n_cases = 65536
hash = "eb759619caf694dd7b9864e62c0952b9180da43badb47b90b5d47ce0c73d2175"
