["commonware_coding::no_coding::conformance::CodecConformance<ReShard>"]
n_cases = 65536
hash = "07854d2fef297a06ba81685e660c332de36d5d18d546927d30daad6d7fda1541"

["commonware_coding::no_coding::conformance::CodecConformance<Shard>"]
n_cases = 65536
hash = "edc22446bb2952609d0c8daccf2d22f8ad2b71eedfcf45296c3f4db49d78404a"

["commonware_coding::reed_solomon::tests::conformance::CodecConformance<Chunk<Sha256>>"]
n_cases = 65536
hash = "aa8512bb8e86e967833edd1a6cc806280d5e7334e9dc8428a098de9204db12d1"

["commonware_coding::test::conformance::CodecConformance<Config>"]
n_cases = 65536
hash = "1a412c5c279f981857081765537b85474184048d1b17053394f94fc42ac1dbf4"

["commonware_coding::zoda::tests::conformance::CodecConformance<ReShard<Sha256>>"]
n_cases = 65536
hash = "ebbbe08eb9beb1c5215a5d67ad9deddaef7c54920e53a751b56a8261e60e0e52"

["commonware_coding::zoda::tests::conformance::CodecConformance<Shard<Sha256>>"]
n_cases = 65536
hash = "929ce4f95f9d5784f995c52b7e5cde8b62663ab068848925314dc9f80eb27d34"
