[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
solc = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false

# Verbosity
verbosity = 2

# Testing
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15 }

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 20 }
verbosity = 4

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"

[doc]
out = "docs"
title = "Commonware Solidity Contracts"
