["commonware_consensus::aggregation::types::tests::conformance::Ack<MinSig, Sha256Digest>"]
n_cases = 65536
hash = "650f939707e2af1e00091f813437689bebd63e401952cd34ae967511e8802366"

["commonware_consensus::aggregation::types::tests::conformance::Activity<MinSig, Sha256Digest>"]
n_cases = 65536
hash = "6498f5323f4bef33ab441bb988081591ac315f55cd78f85bad9f0a7dcd03f579"

["commonware_consensus::aggregation::types::tests::conformance::Certificate<MinSig, Sha256Digest>"]
n_cases = 65536
hash = "6d62a98f635a930dcf01f2d5709f70190ef916cce774b7483eaf0092f0b5e1dc"

["commonware_consensus::aggregation::types::tests::conformance::Item<Sha256Digest>"]
n_cases = 65536
hash = "69536ce6262449bc22fd256943545a3c9d8c5290b67a9a6e8396a5e5cf761961"

["commonware_consensus::aggregation::types::tests::conformance::TipAck<MinSig, Sha256Digest>"]
n_cases = 65536
hash = "d22d425105d9dda042400a4040dfd06ddcc61957cffebad4b2d5c527979b07f3"

["commonware_consensus::marshal::ingress::handler::tests::conformance::Request<B>"]
n_cases = 65536
hash = "85cd899b2ae04636d34a4559d6ffdde0e186f3bd8045282a832868491c608e6f"

["commonware_consensus::ordered_broadcast::types::tests::conformance::Ack<PublicKey, MinPk, Sha256Digest>"]
n_cases = 65536
hash = "d77c48b9ee8b47ab689c67eff36add26f5cb503f615e971d0695cf8f99730e54"

["commonware_consensus::ordered_broadcast::types::tests::conformance::Activity<PublicKey, MinPk, Sha256Digest>"]
n_cases = 65536
hash = "902584ad8634ae1eea9551343feddaf0c8b19cc1ca9bafa949c5fe07f61397ca"

["commonware_consensus::ordered_broadcast::types::tests::conformance::Chunk<PublicKey, Sha256Digest>"]
n_cases = 65536
hash = "b62ae4cd0dfe7ccd2193c2294be33784f37b1bdd9e4f8a6db640e745495f6e64"

["commonware_consensus::ordered_broadcast::types::tests::conformance::Lock<PublicKey, MinPk, Sha256Digest>"]
n_cases = 65536
hash = "1ba3de6600c32bad42e2a70440a5fcb0ff4970866cd12fa955c1ccdec6ae0704"

["commonware_consensus::ordered_broadcast::types::tests::conformance::Node<PublicKey, MinPk, Sha256Digest>"]
n_cases = 65536
hash = "ce5158fafa28b1d9f033a19c5d33fa9d91f6a8940bbd5d42312d0e88804cdb0e"

["commonware_consensus::ordered_broadcast::types::tests::conformance::Parent<MinPk, Sha256Digest>"]
n_cases = 65536
hash = "f46dbf29df8571c17a69fbde128c4c62af0efdc3566b945f8add9938071c21db"

["commonware_consensus::ordered_broadcast::types::tests::conformance::Proposal<PublicKey, Sha256Digest>"]
n_cases = 65536
hash = "9d2ee4f3c6bf86521c09f8858683de48d6310a987643ee379c143480fc7e9a34"

["commonware_consensus::simplex::signing_scheme::bls12381_multisig::tests::conformance::Certificate<MinSig>"]
n_cases = 65536
hash = "300d04d83f33581f5bce771224f35a4f41a50887e6f83648a43013d8e8292815"

["commonware_consensus::simplex::signing_scheme::bls12381_threshold::tests::conformance::Seed<MinSig>"]
n_cases = 65536
hash = "d3cddac59b7f95fdf7d6dcda64b20bb685800ec87ea01a643c4fa5d3f8f71eed"

["commonware_consensus::simplex::signing_scheme::bls12381_threshold::tests::conformance::Signature<MinSig>"]
n_cases = 65536
hash = "030caacb9ab46d08601977418808dc5ff729bddb9f6bb2ea685920539b69ecfb"

["commonware_consensus::simplex::signing_scheme::ed25519::tests::conformance::Certificate"]
n_cases = 65536
hash = "eab4ff22bb7ed99fd73107c8b067e39bd25813b65614df95b4b5c46a312557ad"

["commonware_consensus::simplex::signing_scheme::utils::tests::conformance::Signers"]
n_cases = 65536
hash = "41ef7a306dd2032d7d1b73fe2799cff6f2e8fb1edcd02a0b9798f18f900a19fa"

["commonware_consensus::simplex::types::tests::conformance::Activity<Scheme, Sha256Digest>"]
n_cases = 65536
hash = "a8ef2ff63052b8bd3f724b7e74e11771b65762dacbbb3810bfe85778f929b84b"

["commonware_consensus::simplex::types::tests::conformance::Artifact<Scheme, Sha256Digest>"]
n_cases = 65536
hash = "6a9dcfd0a5973534d017f9fb957e9f4505edacc205183fb0d9baa69de5b1e635"

["commonware_consensus::simplex::types::tests::conformance::Backfiller<Scheme, Sha256Digest>"]
n_cases = 65536
hash = "080be68d5a9b2b564b6c1593c438884daaf2e077c6a04dd9f33feac422e4e36a"

["commonware_consensus::simplex::types::tests::conformance::Certificate<Scheme, Sha256Digest>"]
n_cases = 65536
hash = "a78db937a58c2ba47a07e614a1b1d38c71b8529a9fd55ae8672ae54142b7d49c"

["commonware_consensus::simplex::types::tests::conformance::ConflictingFinalize<Scheme, Sha256Digest>"]
n_cases = 65536
hash = "149f8d53497c89a061e4554cbd1011da79434bbcb3df31b1595a4193a1974ff0"

["commonware_consensus::simplex::types::tests::conformance::ConflictingNotarize<Scheme, Sha256Digest>"]
n_cases = 65536
hash = "149f8d53497c89a061e4554cbd1011da79434bbcb3df31b1595a4193a1974ff0"

["commonware_consensus::simplex::types::tests::conformance::Finalization<Scheme, Sha256Digest>"]
n_cases = 65536
hash = "aab95f3f91f700f11302e98d1e13198d8f6ff2c5d852a27fbe659b4bb45c7e0e"

["commonware_consensus::simplex::types::tests::conformance::Finalize<Scheme, Sha256Digest>"]
n_cases = 65536
hash = "0094d2b51f90c9c4c43dd7a8b4efaea3682b5622b4e181a9fdf520683f30e83d"

["commonware_consensus::simplex::types::tests::conformance::Notarization<Scheme, Sha256Digest>"]
n_cases = 65536
hash = "aab95f3f91f700f11302e98d1e13198d8f6ff2c5d852a27fbe659b4bb45c7e0e"

["commonware_consensus::simplex::types::tests::conformance::Notarize<Scheme, Sha256Digest>"]
n_cases = 65536
hash = "0094d2b51f90c9c4c43dd7a8b4efaea3682b5622b4e181a9fdf520683f30e83d"

["commonware_consensus::simplex::types::tests::conformance::Nullification<Scheme>"]
n_cases = 65536
hash = "a14879072714bf352f641941c2f0c278f590863734071a881286a49b930c7b60"

["commonware_consensus::simplex::types::tests::conformance::Nullify<Scheme>"]
n_cases = 65536
hash = "5ded83d1480b4779ac6427e9afc4c3c2f982c8af8a97f844cfd7b36b29357921"

["commonware_consensus::simplex::types::tests::conformance::NullifyFinalize<Scheme, Sha256Digest>"]
n_cases = 65536
hash = "f6376a2e5e1d5bd015a0d2071acdecc7afe182276784fd148e541249969c6546"

["commonware_consensus::simplex::types::tests::conformance::Proposal<Sha256Digest>"]
n_cases = 65536
hash = "c5274c98a6c936c91f380261cff61c2dc9988e5f28700f0d9cb1b25346d1ffc3"

["commonware_consensus::simplex::types::tests::conformance::Request"]
n_cases = 65536
hash = "6f852b6ad6e5dd77804d80781b03c808e186e7e7c5611752f124c625c5c3ee17"

["commonware_consensus::simplex::types::tests::conformance::Response<Scheme, Sha256Digest>"]
n_cases = 65536
hash = "37c0c4f2dd328ed18a8f29fb73ca7c82c4008e49ea00243ffb3e024873a5b565"

["commonware_consensus::simplex::types::tests::conformance::Signature<Scheme>"]
n_cases = 65536
hash = "4cc8b67162e04fbfbc90d730bbc0eed9774dfb882f2644fe49dd42df9a5305a6"

["commonware_consensus::simplex::types::tests::conformance::Vote<Scheme, Sha256Digest>"]
n_cases = 65536
hash = "331dd41427ed13d34cfd76e63c63ab65b6ca0830af1229f4b4ae8f6346abe598"

["commonware_consensus::types::tests::conformance::Epoch"]
n_cases = 65536
hash = "56ab85978136cb50f12ea89c8d25ce24451788172fe9d3d3c063f7ae6342d279"

["commonware_consensus::types::tests::conformance::Round"]
n_cases = 65536
hash = "d8ccba2653a5a2e5e317f0f365edbfc4845e3dc4325daefe0b43ca75920a654c"

["commonware_consensus::types::tests::conformance::View"]
n_cases = 65536
hash = "56ab85978136cb50f12ea89c8d25ce24451788172fe9d3d3c063f7ae6342d279"
