["commonware_consensus::aggregation::types::tests::conformance::CodecConformance<Ack<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "f53d34477165ef9764e4f2859e42c837f778c088a91ab69a6a7605ca56ff77c9"

["commonware_consensus::aggregation::types::tests::conformance::CodecConformance<Activity<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "1f25d8ef3c67a8741ee8f566410e6bad03afa1aa3ce8b569ad33a904403dc0d5"

["commonware_consensus::aggregation::types::tests::conformance::CodecConformance<Certificate<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "fde109e77996588a9cf8f9b723a9521d26148c0337b655f3c4cf0d92e9b12ff4"

["commonware_consensus::aggregation::types::tests::conformance::CodecConformance<Item<Sha256Digest>>"]
n_cases = 65536
hash = "55b287b5530fc9ba77c45ec5030ada38f86b2ddf66a1595fde27d4699667b1a3"

["commonware_consensus::aggregation::types::tests::conformance::CodecConformance<TipAck<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "924a77caeabb871baa8ac0ccd93a2e53da86f124b0dd5b9b0a383273fab42b6c"

["commonware_consensus::marshal::ingress::handler::tests::conformance::CodecConformance<Request<B>>"]
n_cases = 65536
hash = "481cd68f2e6452c0dda512c75d74ddd2e19ac6c9fb19c642c1a152a0d830c1b2"

["commonware_consensus::ordered_broadcast::types::tests::conformance::CodecConformance<Ack<PublicKey,Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "6aa909d1f8ad45b30cce5169dd05bb743a3259a9d6612997879fb1057db01fa9"

["commonware_consensus::ordered_broadcast::types::tests::conformance::CodecConformance<Activity<PublicKey,Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "030e7f6899fbbfd76a7757cfdaa57b400b4d0bc7662e883b304514e2a9bfb404"

["commonware_consensus::ordered_broadcast::types::tests::conformance::CodecConformance<Chunk<PublicKey,Sha256Digest>>"]
n_cases = 65536
hash = "43624c9e7ce355baebf32ab6e76db21cb5bf08005396ba43dae96b3a86f3a535"

["commonware_consensus::ordered_broadcast::types::tests::conformance::CodecConformance<Lock<PublicKey,Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "32eac601e1ec919be9e8f502a47c8cd64e8feb61701689d2f9ff6f0a8ebafb03"

["commonware_consensus::ordered_broadcast::types::tests::conformance::CodecConformance<Node<PublicKey,Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "b2dfff5e68de39db6881cfd7c5f95397f4330193b8eca5155a716266e53ea921"

["commonware_consensus::ordered_broadcast::types::tests::conformance::CodecConformance<Parent<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "c830d0e3842c1f2ef26f08ee762995942bfbbc722ca9c5e8e6a87c3dbe05c70d"

["commonware_consensus::ordered_broadcast::types::tests::conformance::CodecConformance<Proposal<PublicKey,Sha256Digest>>"]
n_cases = 65536
hash = "6fc6f17d8734a14fb841a8acc1a39cda7519bdd025700663e260d3b000c9c5c6"

["commonware_consensus::simplex::elector::tests::conformance::RandomSelectLeaderConformance"]
n_cases = 512
hash = "4df7290375d7ae3b005cfad96dc5fc091bdce4a246665f94b79acf34159a3945"

["commonware_consensus::simplex::elector::tests::conformance::RoundRobinShuffleConformance"]
n_cases = 512
hash = "d6232310a3adc5cc8bf0767d095251f25211f165419372a5fe6b4ed7b06dd765"

["commonware_consensus::simplex::scheme::bls12381_threshold::tests::conformance::CodecConformance<Seed<MinSig>>"]
n_cases = 65536
hash = "d3cddac59b7f95fdf7d6dcda64b20bb685800ec87ea01a643c4fa5d3f8f71eed"

["commonware_consensus::simplex::scheme::bls12381_threshold::tests::conformance::CodecConformance<Signature<MinSig>>"]
n_cases = 65536
hash = "030caacb9ab46d08601977418808dc5ff729bddb9f6bb2ea685920539b69ecfb"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Activity<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "15a849588cb0e5ea44d62c364c789aa564045c970b830b449b74a1f34720f799"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Artifact<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "076241e74a3f2b0da47792d76277bd4f3b617ad429f298d887151d5dae2d42af"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Backfiller<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "c81cf2317351865d6a9786a60934995b2693cc759350a853bab7e277f758b5e6"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Certificate<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "1422a1e4db078efe00f3f8a5b391d315dc4661f29d24515144a74c65d84a320f"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<ConflictingFinalize<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "ae3440a50566a8e2108c272e2934e2bd28a39715c2d6077ccda329d5d19c5357"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<ConflictingNotarize<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "ae3440a50566a8e2108c272e2934e2bd28a39715c2d6077ccda329d5d19c5357"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Finalization<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "efbd478fdec6e832ffa445bf9cf0282b496bb0cbc45d6e0cf15281cd733b9978"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Finalize<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "182a3d295140ffd4ea33fe5bbfd2b09156c76c4dcde06e71707ac3479345fa0c"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Notarization<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "efbd478fdec6e832ffa445bf9cf0282b496bb0cbc45d6e0cf15281cd733b9978"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Notarize<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "182a3d295140ffd4ea33fe5bbfd2b09156c76c4dcde06e71707ac3479345fa0c"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Nullification<Scheme>>"]
n_cases = 65536
hash = "a14879072714bf352f641941c2f0c278f590863734071a881286a49b930c7b60"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Nullify<Scheme>>"]
n_cases = 65536
hash = "1430b3fac9de5758b9d00c8793d56fc57d1eddbf5ce2fd4f24d2229e4b15c226"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<NullifyFinalize<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "8681786700e24b08366664c9c76a1a4b144ef7881b13c6468bb5ca78175baa09"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Proposal<Sha256Digest>>"]
n_cases = 65536
hash = "4ba1f5b5cbf271ae45313d8ac48b05c010166ca743334b9b8051a4a610c58fe7"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Request>"]
n_cases = 65536
hash = "6f852b6ad6e5dd77804d80781b03c808e186e7e7c5611752f124c625c5c3ee17"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Response<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "6ad91c2b61600699c399c20abb6e9f948bf95ac413363c325226d327bbb37456"

["commonware_consensus::simplex::types::tests::conformance::CodecConformance<Vote<Scheme,Sha256Digest>>"]
n_cases = 65536
hash = "9eefedcb37bd0e098bcf47cf6135148900755f3eeca78f30b013433fe368678f"

["commonware_consensus::types::tests::conformance::CodecConformance<Epoch>"]
n_cases = 65536
hash = "56ab85978136cb50f12ea89c8d25ce24451788172fe9d3d3c063f7ae6342d279"

["commonware_consensus::types::tests::conformance::CodecConformance<Height>"]
n_cases = 65536
hash = "56ab85978136cb50f12ea89c8d25ce24451788172fe9d3d3c063f7ae6342d279"

["commonware_consensus::types::tests::conformance::CodecConformance<Round>"]
n_cases = 65536
hash = "d8ccba2653a5a2e5e317f0f365edbfc4845e3dc4325daefe0b43ca75920a654c"

["commonware_consensus::types::tests::conformance::CodecConformance<View>"]
n_cases = 65536
hash = "56ab85978136cb50f12ea89c8d25ce24451788172fe9d3d3c063f7ae6342d279"
