["commonware_cryptography::blake3::tests::conformance::Digest"]
n_cases = 1024
hash = "e7b94402b6621a7345af31d64a348f1686ded896cd4eb999376d162a748f2d6f"

["commonware_cryptography::bloomfilter::tests::conformance::BloomFilter"]
n_cases = 1024
hash = "9dc837e220a8de29ce0b370754c50a4e62f90e99665722fe6ed57198d0f05820"

["commonware_cryptography::ed25519::scheme::tests::conformance::PrivateKey"]
n_cases = 1024
hash = "929838171771a8edb9f1ab4659035b928e17b218e862a39276fdeab33515277e"

["commonware_cryptography::ed25519::scheme::tests::conformance::PublicKey"]
n_cases = 1024
hash = "977776541e0edf8c34822f4fefe6299d668a1cd43657b2a4b4dbb5f8ca36f6ed"

["commonware_cryptography::ed25519::scheme::tests::conformance::Signature"]
n_cases = 1024
hash = "068f1c5ed28f557da506f5bb3a802790777a429180545aaf09e9ff503d6ccf02"

["commonware_cryptography::sha256::tests::conformance::Digest"]
n_cases = 1024
hash = "e7b94402b6621a7345af31d64a348f1686ded896cd4eb999376d162a748f2d6f"

["commonware_cryptography::transcript::test::conformance::Summary"]
n_cases = 1024
hash = "e7b94402b6621a7345af31d64a348f1686ded896cd4eb999376d162a748f2d6f"
