["commonware_cryptography::blake3::tests::conformance::CodecConformance<Digest>"]
n_cases = 65536
hash = "c0501d4a691d1fccec7c5906e8608228569d24164150edd215838593e3b77512"

["commonware_cryptography::bloomfilter::tests::conformance::CodecConformance<BloomFilter>"]
n_cases = 65536
hash = "a75d6312366816126114abdc9d7fbd246891cab210eeae6a02781625aa1ad6a4"

["commonware_cryptography::bls12381::dkg::test::conformance::CodecConformance<AckOrReveal<ed25519::PublicKey>>"]
n_cases = 65536
hash = "0081c641fd7d19194dcb85e69527d4e4fb6f722f10029ed754813e97da825e89"

["commonware_cryptography::bls12381::dkg::test::conformance::CodecConformance<DealerLog<MinPk,ed25519::PublicKey>>"]
n_cases = 65536
hash = "c4a3575f319b605d8479c569f04cdf73224f6067e5f6f6bab7ac2485245c0382"

["commonware_cryptography::bls12381::dkg::test::conformance::CodecConformance<DealerPrivMsg>"]
n_cases = 65536
hash = "d112d774a4c9b012b53e44dc2a3487a0e2f87cd7b14fb8433ec7cea4997f440a"

["commonware_cryptography::bls12381::dkg::test::conformance::CodecConformance<DealerPubMsg<MinPk>>"]
n_cases = 65536
hash = "3ec46a7e3d5627d15285c6b51e669348bfe988829c7ea493a4bacf5d98d632f7"

["commonware_cryptography::bls12381::dkg::test::conformance::CodecConformance<DealerResult<ed25519::PublicKey>>"]
n_cases = 65536
hash = "06cd5f1dca291e1812e01a82474926520794c8844813d64882c9a1cd6106e771"

["commonware_cryptography::bls12381::dkg::test::conformance::CodecConformance<Output<MinPk,ed25519::PublicKey>>"]
n_cases = 65536
hash = "aa59e152a5402fe91de7af791ee90d0301ac788904b3ee2232c97e049ceacb80"

["commonware_cryptography::bls12381::dkg::test::conformance::CodecConformance<PlayerAck<ed25519::PublicKey>>"]
n_cases = 65536
hash = "0cbb8c8644dffe0be78d1307fb5034dd804921d66799c1aaec3d335b44e9616c"

["commonware_cryptography::bls12381::dkg::test::conformance::CodecConformance<SignedDealerLog<MinPk,ed25519::PrivateKey>>"]
n_cases = 65536
hash = "b4e91bface5ddaa1fac0287e9495e51152b809350a7a42ffb042d43526180146"

["commonware_cryptography::bls12381::primitives::group::tests::conformance::CodecConformance<G1>"]
n_cases = 65536
hash = "5c46f1b09e85d595727cfe40dd5c9687e17ae63fbd162d97bbdd89ea44fa4fd0"

["commonware_cryptography::bls12381::primitives::group::tests::conformance::CodecConformance<G2>"]
n_cases = 65536
hash = "4164fc177bf0652f3711b2d86a975f604fdc5092a1d9c7110223d02d88bf5f79"

["commonware_cryptography::bls12381::primitives::group::tests::conformance::CodecConformance<Scalar>"]
n_cases = 65536
hash = "d112d774a4c9b012b53e44dc2a3487a0e2f87cd7b14fb8433ec7cea4997f440a"

["commonware_cryptography::bls12381::primitives::group::tests::conformance::CodecConformance<Share>"]
n_cases = 65536
hash = "169550a1597994aad7ba634091b89633424be84f6753fe95542d2f3fd4108b9f"

["commonware_cryptography::bls12381::scheme::tests::conformance::CodecConformance<PrivateKey>"]
n_cases = 65536
hash = "aa81d563f32bdf4b936eae0dd1ac81eba6663fd81d23cc1204a25a20abb20b30"

["commonware_cryptography::bls12381::scheme::tests::conformance::CodecConformance<PublicKey>"]
n_cases = 65536
hash = "5ea2cd9db2e4a992cea58f8b05ab8d668e9f46d8f2bb93d29c4cb9889cef8702"

["commonware_cryptography::bls12381::scheme::tests::conformance::CodecConformance<Signature>"]
n_cases = 65536
hash = "47795d1da003840d57a425277356731bb3bebe5ac11c08ab7cb204f5e52b2d62"

["commonware_cryptography::bls12381::tle::tests::conformance::CodecConformance<Ciphertext<MinPk>>"]
n_cases = 65536
hash = "731c5d3dfb09b6e6f1cf50136ba82f036fffab855ec953be59877bb95a48e1dd"

["commonware_cryptography::ed25519::scheme::tests::conformance::CodecConformance<PrivateKey>"]
n_cases = 65536
hash = "3e17c0a4943a83bf61cc55d039570928871866f0d50f8846dfd628a23f00d69e"

["commonware_cryptography::ed25519::scheme::tests::conformance::CodecConformance<PublicKey>"]
n_cases = 65536
hash = "9010ca9b2849258179377f855fb77967ff003c8f349258d868bab76b0bfa1c5a"

["commonware_cryptography::ed25519::scheme::tests::conformance::CodecConformance<Signature>"]
n_cases = 65536
hash = "0cbb8c8644dffe0be78d1307fb5034dd804921d66799c1aaec3d335b44e9616c"

["commonware_cryptography::handshake::key_exchange::conformance::CodecConformance<EphemeralPublicKey>"]
n_cases = 65536
hash = "c0501d4a691d1fccec7c5906e8608228569d24164150edd215838593e3b77512"

["commonware_cryptography::handshake::test::conformance::CodecConformance<Ack>"]
n_cases = 65536
hash = "c0501d4a691d1fccec7c5906e8608228569d24164150edd215838593e3b77512"

["commonware_cryptography::handshake::test::conformance::CodecConformance<Syn<crate::ed25519::Signature>>"]
n_cases = 65536
hash = "6776e093b02edc1c846c2a1f2f7525709a7d51e9743f81ac388cdee53a601aaf"

["commonware_cryptography::handshake::test::conformance::CodecConformance<SynAck<crate::ed25519::Signature>>"]
n_cases = 65536
hash = "b98d0717af705e8b60af88a8337154eaced6659c3cc9f604aa4f55585a28b77f"

["commonware_cryptography::lthash::tests::conformance::CodecConformance<LtHash>"]
n_cases = 65536
hash = "47ab8f97f2b9ff2b56e952c4e219c8c95832cf3a58d5b682cdc769c2ecb79daf"

["commonware_cryptography::secp256r1::common::tests::conformance::CodecConformance<PrivateKeyInner>"]
n_cases = 65536
hash = "3e17c0a4943a83bf61cc55d039570928871866f0d50f8846dfd628a23f00d69e"

["commonware_cryptography::secp256r1::common::tests::conformance::CodecConformance<PublicKeyInner>"]
n_cases = 65536
hash = "b3fde3da5266e1c7eab5ae245257494e658c6c351a99809ca6011d8190bbf456"

["commonware_cryptography::secp256r1::recoverable::tests::conformance::CodecConformance<Signature>"]
n_cases = 65536
hash = "68c8cb64495f2720508aad881b192b24e00e5260780c3ea7c5109ef9097bee30"

["commonware_cryptography::secp256r1::standard::tests::conformance::CodecConformance<Signature>"]
n_cases = 65536
hash = "05880099d66c9e04ab2d4bf5dfa3fecfc4fb114264ca3b4a0c3b4816332414b9"

["commonware_cryptography::sha256::tests::conformance::CodecConformance<Digest>"]
n_cases = 65536
hash = "c0501d4a691d1fccec7c5906e8608228569d24164150edd215838593e3b77512"

["commonware_cryptography::transcript::test::conformance::CodecConformance<Summary>"]
n_cases = 65536
hash = "c0501d4a691d1fccec7c5906e8608228569d24164150edd215838593e3b77512"
