["commonware_cryptography::blake3::tests::conformance::CodecConformance<Digest>"]
n_cases = 65536
hash = "d01e3ef0dd81919abd3f149649940ae2e8cff6dc4aa9f927d544aece387b12d1"

["commonware_cryptography::bloomfilter::conformance::CodecConformance<BloomFilter>"]
n_cases = 65536
hash = "064cd9eab1a79b2270de039d6105df261954aa1fc8df1fbd55ecf6f18f43f437"

["commonware_cryptography::bloomfilter::conformance::RationalOptimalBits"]
n_cases = 1024
hash = "f631238a016fb44fd2dee9eeb5bd20fc5052f33434810599b8ba6535e2ad8e97"

["commonware_cryptography::bls12381::certificate::multisig::tests::conformance::CodecConformance<Certificate<MinSig>>"]
n_cases = 65536
hash = "ad245f64a57c96036599647eaf509937173e9de01503a9e6494f29571191ade1"

["commonware_cryptography::bls12381::certificate::threshold::tests::conformance::CodecConformance<Certificate<MinSig>>"]
n_cases = 65536
hash = "ba2d888e6d1050e6a361aa79430c1bb03d90eb8e74b9715b1d7d01c35a495e1d"

["commonware_cryptography::bls12381::dkg::test::conformance::CodecConformance<AckOrReveal<ed25519::PublicKey>>"]
n_cases = 65536
hash = "97c266fb7821326e6333be0859025c774220c8d010e488d2fd13a743e4135f64"

["commonware_cryptography::bls12381::dkg::test::conformance::CodecConformance<DealerLog<MinPk,ed25519::PublicKey>>"]
n_cases = 65536
hash = "ef8d69a3cbafc5e3f8f98755337acacc6609e92d3fdee0e4576481190cb421b4"

["commonware_cryptography::bls12381::dkg::test::conformance::CodecConformance<DealerPrivMsg>"]
n_cases = 65536
hash = "2d443ed310b383cab74abec888d0637ab81435779e274ed7be84adc7b10e2f86"

["commonware_cryptography::bls12381::dkg::test::conformance::CodecConformance<DealerPubMsg<MinPk>>"]
n_cases = 65536
hash = "0a15ca78d654be68bb78cf58cfd1da568f8f1585878f081735939f02da161b22"

["commonware_cryptography::bls12381::dkg::test::conformance::CodecConformance<DealerResult<ed25519::PublicKey>>"]
n_cases = 65536
hash = "1a05e4e910dd186bd81189d79eaf1b4c211012d07f534ddaa38ab9705d80fa62"

["commonware_cryptography::bls12381::dkg::test::conformance::CodecConformance<Output<MinPk,ed25519::PublicKey>>"]
n_cases = 65536
hash = "9ac8b8c69d40191f12ad840cbd653b29a73e91c9f4156f82bf3b5e0c746e372c"

["commonware_cryptography::bls12381::dkg::test::conformance::CodecConformance<PlayerAck<ed25519::PublicKey>>"]
n_cases = 65536
hash = "0cbb8c8644dffe0be78d1307fb5034dd804921d66799c1aaec3d335b44e9616c"

["commonware_cryptography::bls12381::dkg::test::conformance::CodecConformance<SignedDealerLog<MinPk,ed25519::PrivateKey>>"]
n_cases = 65536
hash = "fca94fb3b0df54a6a34edfbb8aeef28490262daf97870e12f869aee6cf7f7e67"

["commonware_cryptography::bls12381::primitives::group::tests::conformance::CodecConformance<G1>"]
n_cases = 65536
hash = "ba2d888e6d1050e6a361aa79430c1bb03d90eb8e74b9715b1d7d01c35a495e1d"

["commonware_cryptography::bls12381::primitives::group::tests::conformance::CodecConformance<G2>"]
n_cases = 65536
hash = "683a309d5fefb8e0ab6778c22e66bd43e139c5f56204df932fd81052792adf4b"

["commonware_cryptography::bls12381::primitives::group::tests::conformance::CodecConformance<Private>"]
n_cases = 65536
hash = "2d443ed310b383cab74abec888d0637ab81435779e274ed7be84adc7b10e2f86"

["commonware_cryptography::bls12381::primitives::group::tests::conformance::CodecConformance<Scalar>"]
n_cases = 65536
hash = "2d443ed310b383cab74abec888d0637ab81435779e274ed7be84adc7b10e2f86"

["commonware_cryptography::bls12381::primitives::group::tests::conformance::CodecConformance<Share>"]
n_cases = 65536
hash = "7595e042deed41454a74a89e13ecb304a04d0087c9d0760c2ed7940b06a53d78"

["commonware_cryptography::bls12381::primitives::ops::aggregate::tests::conformance::CodecConformance<Message<MinSig>>"]
n_cases = 65536
hash = "ba2d888e6d1050e6a361aa79430c1bb03d90eb8e74b9715b1d7d01c35a495e1d"

["commonware_cryptography::bls12381::primitives::ops::aggregate::tests::conformance::CodecConformance<PublicKey<MinSig>>"]
n_cases = 65536
hash = "683a309d5fefb8e0ab6778c22e66bd43e139c5f56204df932fd81052792adf4b"

["commonware_cryptography::bls12381::primitives::ops::aggregate::tests::conformance::CodecConformance<Signature<MinSig>>"]
n_cases = 65536
hash = "ba2d888e6d1050e6a361aa79430c1bb03d90eb8e74b9715b1d7d01c35a495e1d"

["commonware_cryptography::bls12381::primitives::variant::tests::conformance::CodecConformance<PartialSignature<MinPk>>"]
n_cases = 65536
hash = "f022eac985ba0e1cd501cb3988f8d05f0c7e4c491447ff069e0a5ae8e93eac4a"

["commonware_cryptography::bls12381::primitives::variant::tests::conformance::CodecConformance<PartialSignature<MinSig>>"]
n_cases = 65536
hash = "7eb431ae7ecc27666f9ca1614f23940fedbc7a49eb59ef2af0d95af422fb73a4"

["commonware_cryptography::bls12381::scheme::tests::conformance::CodecConformance<PrivateKey>"]
n_cases = 65536
hash = "aa81d563f32bdf4b936eae0dd1ac81eba6663fd81d23cc1204a25a20abb20b30"

["commonware_cryptography::bls12381::scheme::tests::conformance::CodecConformance<PublicKey>"]
n_cases = 65536
hash = "5ea2cd9db2e4a992cea58f8b05ab8d668e9f46d8f2bb93d29c4cb9889cef8702"

["commonware_cryptography::bls12381::scheme::tests::conformance::CodecConformance<Signature>"]
n_cases = 65536
hash = "dcc604b71699aa675d3f3a033a6975b8fb9e1dde6809ba5c37d516cf13dce75d"

["commonware_cryptography::bls12381::tle::tests::conformance::CodecConformance<Ciphertext<MinPk>>"]
n_cases = 65536
hash = "d764de51d89d256bfd2ffcf39a3497fa3e5e27a60cc7da5363b47f5a9390f655"

["commonware_cryptography::certificate::tests::conformance::CodecConformance<Attestation<Scheme>>"]
n_cases = 65536
hash = "42867052b1619b912d08f0a6bf5f964f587897a0eed8612732fd27813f6c03bd"

["commonware_cryptography::certificate::tests::conformance::CodecConformance<Signers>"]
n_cases = 65536
hash = "41ef7a306dd2032d7d1b73fe2799cff6f2e8fb1edcd02a0b9798f18f900a19fa"

["commonware_cryptography::crc32::tests::conformance::CodecConformance<Digest>"]
n_cases = 65536
hash = "d0101a0688d45c8f7428b3861ed6e7e77c2ed25033cb7d6b47b3fa58148a3f18"

["commonware_cryptography::ed25519::certificate::tests::conformance::CodecConformance<Certificate>"]
n_cases = 65536
hash = "eab4ff22bb7ed99fd73107c8b067e39bd25813b65614df95b4b5c46a312557ad"

["commonware_cryptography::ed25519::scheme::tests::conformance::CodecConformance<PrivateKey>"]
n_cases = 65536
hash = "3e17c0a4943a83bf61cc55d039570928871866f0d50f8846dfd628a23f00d69e"

["commonware_cryptography::ed25519::scheme::tests::conformance::CodecConformance<PublicKey>"]
n_cases = 65536
hash = "9010ca9b2849258179377f855fb77967ff003c8f349258d868bab76b0bfa1c5a"

["commonware_cryptography::ed25519::scheme::tests::conformance::CodecConformance<Signature>"]
n_cases = 65536
hash = "0cbb8c8644dffe0be78d1307fb5034dd804921d66799c1aaec3d335b44e9616c"

["commonware_cryptography::handshake::conformance::Handshake"]
n_cases = 4096
hash = "ed6ff974cf9460e825683ccaef3946e46c0db7281b41209dcee641ad1d46db77"

["commonware_cryptography::handshake::key_exchange::conformance::CodecConformance<EphemeralPublicKey>"]
n_cases = 65536
hash = "c0501d4a691d1fccec7c5906e8608228569d24164150edd215838593e3b77512"

["commonware_cryptography::handshake::test::conformance::CodecConformance<Ack>"]
n_cases = 65536
hash = "c0501d4a691d1fccec7c5906e8608228569d24164150edd215838593e3b77512"

["commonware_cryptography::handshake::test::conformance::CodecConformance<Syn<crate::ed25519::Signature>>"]
n_cases = 65536
hash = "6776e093b02edc1c846c2a1f2f7525709a7d51e9743f81ac388cdee53a601aaf"

["commonware_cryptography::handshake::test::conformance::CodecConformance<SynAck<crate::ed25519::Signature>>"]
n_cases = 65536
hash = "b98d0717af705e8b60af88a8337154eaced6659c3cc9f604aa4f55585a28b77f"

["commonware_cryptography::lthash::tests::conformance::CodecConformance<LtHash>"]
n_cases = 65536
hash = "47ab8f97f2b9ff2b56e952c4e219c8c95832cf3a58d5b682cdc769c2ecb79daf"

["commonware_cryptography::secp256r1::certificate::tests::conformance::CodecConformance<Certificate>"]
n_cases = 1024
hash = "c708aa3df9cc2918aaf2d8db673c96729a2d2fd41b470ac5f6843489fc380951"

["commonware_cryptography::secp256r1::common::tests::conformance::CodecConformance<PrivateKeyInner>"]
n_cases = 1024
hash = "929838171771a8edb9f1ab4659035b928e17b218e862a39276fdeab33515277e"

["commonware_cryptography::secp256r1::common::tests::conformance::CodecConformance<PublicKeyInner>"]
n_cases = 1024
hash = "5ae65341bf87d6392c4b512d423053bff0a6f5a60c710f6eb3fbba8b6a84930d"

["commonware_cryptography::secp256r1::recoverable::tests::conformance::CodecConformance<Signature>"]
n_cases = 1024
hash = "f690616acff898e1ca0b5e43923709b8e46d30aae90faf135b424a03c55d32b5"

["commonware_cryptography::secp256r1::standard::tests::conformance::CodecConformance<Signature>"]
n_cases = 1024
hash = "b77c35491bd5115cfa2f9a9e0d4f4e4f9f23b1675ead3c9a73160ef45b60cbfc"

["commonware_cryptography::sha256::tests::conformance::CodecConformance<Digest>"]
n_cases = 65536
hash = "d65ced18cacd65769e8f9732131a06216e6600d5a115c4ed7483a8530813ddcd"

["commonware_cryptography::transcript::test::conformance::CodecConformance<Summary>"]
n_cases = 65536
hash = "c0501d4a691d1fccec7c5906e8608228569d24164150edd215838593e3b77512"
