[["()".cases]]
seed = 0
expected = ""

[["()".cases]]
seed = 1
expected = ""

[["()".cases]]
seed = 2
expected = ""

[["()".cases]]
seed = 3
expected = ""

[["()".cases]]
seed = 4
expected = ""

[["(u32, u32)".cases]]
seed = 0
expected = "a79a3b6cb585f767"

[["(u32, u32)".cases]]
seed = 1
expected = "8ca40db167094cea"

[["(u32, u32)".cases]]
seed = 2
expected = "318a1bc5e19f8bc9"

[["(u32, u32)".cases]]
seed = 3
expected = "1bbce95d9f7acbb4"

[["(u32, u32)".cases]]
seed = 4
expected = "fcaecf22b9ede492"

[["(u32, u32, u32)".cases]]
seed = 0
expected = "a79a3b6cb585f767bad8c037"

[["(u32, u32, u32)".cases]]
seed = 1
expected = "8ca40db167094ceafc0e8e6b"

[["(u32, u32, u32)".cases]]
seed = 2
expected = "318a1bc5e19f8bc985b46530"

[["(u32, u32, u32)".cases]]
seed = 3
expected = "1bbce95d9f7acbb4a391f99c"

[["(u32, u32, u32)".cases]]
seed = 4
expected = "fcaecf22b9ede492a601aeb0"

[["(u32, u32, u32, u32)".cases]]
seed = 0
expected = "a79a3b6cb585f767bad8c0377746a55f"

[["(u32, u32, u32, u32)".cases]]
seed = 1
expected = "8ca40db167094ceafc0e8e6b149406d8"

[["(u32, u32, u32, u32)".cases]]
seed = 2
expected = "318a1bc5e19f8bc985b465308c65f8c9"

[["(u32, u32, u32, u32)".cases]]
seed = 3
expected = "1bbce95d9f7acbb4a391f99c14d03022"

[["(u32, u32, u32, u32)".cases]]
seed = 4
expected = "fcaecf22b9ede492a601aeb011df953a"

[["(u32, u32, u32, u32, u32)".cases]]
seed = 0
expected = "a79a3b6cb585f767bad8c0377746a55f81e2a6e6"

[["(u32, u32, u32, u32, u32)".cases]]
seed = 1
expected = "8ca40db167094ceafc0e8e6b149406d836070665"

[["(u32, u32, u32, u32, u32)".cases]]
seed = 2
expected = "318a1bc5e19f8bc985b465308c65f8c908434c19"

[["(u32, u32, u32, u32, u32)".cases]]
seed = 3
expected = "1bbce95d9f7acbb4a391f99c14d03022ea7442b4"

[["(u32, u32, u32, u32, u32)".cases]]
seed = 4
expected = "fcaecf22b9ede492a601aeb011df953a7b9b27f1"

[["(u32, u32, u32, u32, u32, u32)".cases]]
seed = 0
expected = "a79a3b6cb585f767bad8c0377746a55f81e2a6e6b2fb0d32"

[["(u32, u32, u32, u32, u32, u32)".cases]]
seed = 1
expected = "8ca40db167094ceafc0e8e6b149406d83607066598b82b03"

[["(u32, u32, u32, u32, u32, u32)".cases]]
seed = 2
expected = "318a1bc5e19f8bc985b465308c65f8c908434c19ca0c5743"

[["(u32, u32, u32, u32, u32, u32)".cases]]
seed = 3
expected = "1bbce95d9f7acbb4a391f99c14d03022ea7442b452a36454"

[["(u32, u32, u32, u32, u32, u32)".cases]]
seed = 4
expected = "fcaecf22b9ede492a601aeb011df953a7b9b27f1e0e4dd6b"

[["BTreeMap<u32, u32>".cases]]
seed = 0
expected = "00"

[["BTreeMap<u32, u32>".cases]]
seed = 1
expected = "01ea8ca40d6b67094c"

[["BTreeMap<u32, u32>".cases]]
seed = 2
expected = "040c5743080a72c2cac9318a1b30e19f8bdb7ab4302e8a2b41f8c985b44c198c65"

[["BTreeMap<u32, u32>".cases]]
seed = 3
expected = "023022a39142b414d0b41bbce99c9f7acb"

[["BTreeMap<u32, u32>".cases]]
seed = 4
expected = "00"

[["BTreeSet<u8>".cases]]
seed = 0
expected = "00"

[["BTreeSet<u8>".cases]]
seed = 1
expected = "010d"

[["BTreeSet<u8>".cases]]
seed = 2
expected = "011b"

[["BTreeSet<u8>".cases]]
seed = 3
expected = "01e9"

[["BTreeSet<u8>".cases]]
seed = 4
expected = "00"

[[Bytes.cases]]
seed = 0
expected = "049a678537"

[[Bytes.cases]]
seed = 1
expected = "01a4"

[[Bytes.cases]]
seed = 2
expected = "068ac99f30b4c9"

[[Bytes.cases]]
seed = 3
expected = "06bcb47a9c9122"

[[Bytes.cases]]
seed = 4
expected = "01ae"

[["HashMap<u32, u32>".cases]]
seed = 0
expected = "00"

[["HashMap<u32, u32>".cases]]
seed = 1
expected = "01ea8ca40d6b67094c"

[["HashMap<u32, u32>".cases]]
seed = 2
expected = "040c5743080a72c2cac9318a1b30e19f8bdb7ab4302e8a2b41f8c985b44c198c65"

[["HashMap<u32, u32>".cases]]
seed = 3
expected = "023022a39142b414d0b41bbce99c9f7acb"

[["HashMap<u32, u32>".cases]]
seed = 4
expected = "00"

[["HashSet<u32>".cases]]
seed = 0
expected = "00"

[["HashSet<u32>".cases]]
seed = 1
expected = "01ea8ca40d"

[["HashSet<u32>".cases]]
seed = 2
expected = "026530e19fc9318a1b"

[["HashSet<u32>".cases]]
seed = 3
expected = "03b41bbce9d03022a3f99c9f7a"

[["HashSet<u32>".cases]]
seed = 4
expected = "00"

[[Ipv4Addr.cases]]
seed = 0
expected = "a79a3b6c"

[[Ipv4Addr.cases]]
seed = 1
expected = "8ca40db1"

[[Ipv4Addr.cases]]
seed = 2
expected = "318a1bc5"

[[Ipv4Addr.cases]]
seed = 3
expected = "1bbce95d"

[[Ipv4Addr.cases]]
seed = 4
expected = "fcaecf22"

[[Ipv6Addr.cases]]
seed = 0
expected = "7746a55fbad8c037b585f767a79a3b6c"

[[Ipv6Addr.cases]]
seed = 1
expected = "149406d8fc0e8e6b67094cea8ca40db1"

[[Ipv6Addr.cases]]
seed = 2
expected = "8c65f8c985b46530e19f8bc9318a1bc5"

[[Ipv6Addr.cases]]
seed = 3
expected = "14d03022a391f99c9f7acbb41bbce95d"

[[Ipv6Addr.cases]]
seed = 4
expected = "11df953aa601aeb0b9ede492fcaecf22"

[["Option<u32>".cases]]
seed = 0
expected = "0108d17eae"

[["Option<u32>".cases]]
seed = 1
expected = "01ee3d2b28"

[["Option<u32>".cases]]
seed = 2
expected = "00"

[["Option<u32>".cases]]
seed = 3
expected = "01d3038337"

[["Option<u32>".cases]]
seed = 4
expected = "00"

[["Option<u64>".cases]]
seed = 0
expected = "00"

[["Option<u64>".cases]]
seed = 1
expected = "016b67094cea8ca40d"

[["Option<u64>".cases]]
seed = 2
expected = "0130e19f8bc9318a1b"

[["Option<u64>".cases]]
seed = 3
expected = "019c9f7acbb41bbce9"

[["Option<u64>".cases]]
seed = 4
expected = "00"

[[SocketAddr.cases]]
seed = 0
expected = "06e67746a55fbad8c037b585f767a79a3be2a6"

[[SocketAddr.cases]]
seed = 1
expected = "04ea8ca40d094c"

[[SocketAddr.cases]]
seed = 2
expected = "04c9318a1b9f8b"

[[SocketAddr.cases]]
seed = 3
expected = "04b41bbce97acb"

[[SocketAddr.cases]]
seed = 4
expected = "06f111df953aa601aeb0b9ede492fcaecf9b27"

[[SocketAddrV4.cases]]
seed = 0
expected = "a79a3b6cf767"

[[SocketAddrV4.cases]]
seed = 1
expected = "8ca40db14cea"

[[SocketAddrV4.cases]]
seed = 2
expected = "318a1bc58bc9"

[[SocketAddrV4.cases]]
seed = 3
expected = "1bbce95dcbb4"

[[SocketAddrV4.cases]]
seed = 4
expected = "fcaecf22e492"

[[SocketAddrV6.cases]]
seed = 0
expected = "7746a55fbad8c037b585f767a79a3b6ca6e6"

[[SocketAddrV6.cases]]
seed = 1
expected = "149406d8fc0e8e6b67094cea8ca40db10665"

[[SocketAddrV6.cases]]
seed = 2
expected = "8c65f8c985b46530e19f8bc9318a1bc54c19"

[[SocketAddrV6.cases]]
seed = 3
expected = "14d03022a391f99c9f7acbb41bbce95d42b4"

[[SocketAddrV6.cases]]
seed = 4
expected = "11df953aa601aeb0b9ede492fcaecf2227f1"

[["Vec<u16>".cases]]
seed = 0
expected = "00"

[["Vec<u16>".cases]]
seed = 1
expected = "01a40d"

[["Vec<u16>".cases]]
seed = 2
expected = "058a1b8bc930e185b465f8"

[["Vec<u16>".cases]]
seed = 3
expected = "02bce9cbb4"

[["Vec<u16>".cases]]
seed = 4
expected = "00"

[["Vec<u32>".cases]]
seed = 0
expected = "00"

[["Vec<u32>".cases]]
seed = 1
expected = "01ea8ca40d"

[["Vec<u32>".cases]]
seed = 2
expected = "02c9318a1b6530e19f"

[["Vec<u32>".cases]]
seed = 3
expected = "03b41bbce9f99c9f7ad03022a3"

[["Vec<u32>".cases]]
seed = 4
expected = "00"

[["Vec<u8>".cases]]
seed = 0
expected = "00"

[["Vec<u8>".cases]]
seed = 1
expected = "010d"

[["Vec<u8>".cases]]
seed = 2
expected = "011b"

[["Vec<u8>".cases]]
seed = 3
expected = "01e9"

[["Vec<u8>".cases]]
seed = 4
expected = "00"

[["[u8; 32]".cases]]
seed = 0
expected = "6c3b9aa767f785b537c0d8ba5fa54677e6a6e281320dfbb27c889b8fa460670f"

[["[u8; 32]".cases]]
seed = 1
expected = "b10da48cea4c09676b8e0efcd806941465060736032bb898420d0863dca72538"

[["[u8; 32]".cases]]
seed = 2
expected = "c51b8a31c98b9fe13065b485c9f8658c194c430843570ccac2720a3b30b47adb"

[["[u8; 32]".cases]]
seed = 3
expected = "5de9bc1bb4cb7a9f9cf991a32230d014b44274ea5464a352f089a8cccc486915"

[["[u8; 32]".cases]]
seed = 4
expected = "22cfaefc92e4edb9b0ae01a63a95df11f1279b7b6bdde4e048f6ece8f8c8f2c2"

[[bool.cases]]
seed = 0
expected = "00"

[[bool.cases]]
seed = 1
expected = "01"

[[bool.cases]]
seed = 2
expected = "01"

[[bool.cases]]
seed = 3
expected = "01"

[[bool.cases]]
seed = 4
expected = "00"

[[f32.cases]]
seed = 0
expected = "a79a3b6c"

[[f32.cases]]
seed = 1
expected = "8ca40db1"

[[f32.cases]]
seed = 2
expected = "318a1bc5"

[[f32.cases]]
seed = 3
expected = "1bbce95d"

[[f32.cases]]
seed = 4
expected = "fcaecf22"

[[f64.cases]]
seed = 0
expected = "b585f767a79a3b6c"

[[f64.cases]]
seed = 1
expected = "67094cea8ca40db1"

[[f64.cases]]
seed = 2
expected = "e19f8bc9318a1bc5"

[[f64.cases]]
seed = 3
expected = "9f7acbb41bbce95d"

[[f64.cases]]
seed = 4
expected = "b9ede492fcaecf22"

[[i128.cases]]
seed = 0
expected = "7746a55fbad8c037b585f767a79a3b6c"

[[i128.cases]]
seed = 1
expected = "149406d8fc0e8e6b67094cea8ca40db1"

[[i128.cases]]
seed = 2
expected = "8c65f8c985b46530e19f8bc9318a1bc5"

[[i128.cases]]
seed = 3
expected = "14d03022a391f99c9f7acbb41bbce95d"

[[i128.cases]]
seed = 4
expected = "11df953aa601aeb0b9ede492fcaecf22"

[[i16.cases]]
seed = 0
expected = "3b6c"

[[i16.cases]]
seed = 1
expected = "0db1"

[[i16.cases]]
seed = 2
expected = "1bc5"

[[i16.cases]]
seed = 3
expected = "e95d"

[[i16.cases]]
seed = 4
expected = "cf22"

[[i32.cases]]
seed = 0
expected = "a79a3b6c"

[[i32.cases]]
seed = 1
expected = "8ca40db1"

[[i32.cases]]
seed = 2
expected = "318a1bc5"

[[i32.cases]]
seed = 3
expected = "1bbce95d"

[[i32.cases]]
seed = 4
expected = "fcaecf22"

[[i64.cases]]
seed = 0
expected = "b585f767a79a3b6c"

[[i64.cases]]
seed = 1
expected = "67094cea8ca40db1"

[[i64.cases]]
seed = 2
expected = "e19f8bc9318a1bc5"

[[i64.cases]]
seed = 3
expected = "9f7acbb41bbce95d"

[[i64.cases]]
seed = 4
expected = "b9ede492fcaecf22"

[[i8.cases]]
seed = 0
expected = "6c"

[[i8.cases]]
seed = 1
expected = "b1"

[[i8.cases]]
seed = 2
expected = "c5"

[[i8.cases]]
seed = 3
expected = "5d"

[[i8.cases]]
seed = 4
expected = "22"

[[u128.cases]]
seed = 0
expected = "7746a55fbad8c037b585f767a79a3b6c"

[[u128.cases]]
seed = 1
expected = "149406d8fc0e8e6b67094cea8ca40db1"

[[u128.cases]]
seed = 2
expected = "8c65f8c985b46530e19f8bc9318a1bc5"

[[u128.cases]]
seed = 3
expected = "14d03022a391f99c9f7acbb41bbce95d"

[[u128.cases]]
seed = 4
expected = "11df953aa601aeb0b9ede492fcaecf22"

[[u16.cases]]
seed = 0
expected = "3b6c"

[[u16.cases]]
seed = 1
expected = "0db1"

[[u16.cases]]
seed = 2
expected = "1bc5"

[[u16.cases]]
seed = 3
expected = "e95d"

[[u16.cases]]
seed = 4
expected = "cf22"

[[u32.cases]]
seed = 0
expected = "a79a3b6c"

[[u32.cases]]
seed = 1
expected = "8ca40db1"

[[u32.cases]]
seed = 2
expected = "318a1bc5"

[[u32.cases]]
seed = 3
expected = "1bbce95d"

[[u32.cases]]
seed = 4
expected = "fcaecf22"

[[u64.cases]]
seed = 0
expected = "b585f767a79a3b6c"

[[u64.cases]]
seed = 1
expected = "67094cea8ca40db1"

[[u64.cases]]
seed = 2
expected = "e19f8bc9318a1bc5"

[[u64.cases]]
seed = 3
expected = "9f7acbb41bbce95d"

[[u64.cases]]
seed = 4
expected = "b9ede492fcaecf22"

[[u8.cases]]
seed = 0
expected = "6c"

[[u8.cases]]
seed = 1
expected = "b1"

[[u8.cases]]
seed = 2
expected = "c5"

[[u8.cases]]
seed = 3
expected = "5d"

[[u8.cases]]
seed = 4
expected = "22"
