["commonware_codec::types::btree_map::tests::conformance::BTreeMap<u32, u32>"]
n_cases = 1024
hash = "50faddad1116de4876604ce756fded13f10468fa1ab3da6dc6510cfcb5c48ff4"

["commonware_codec::types::btree_set::tests::conformance::BTreeSet<u8>"]
n_cases = 1024
hash = "f2de124e52a4df6f7d0cebdd1135e1afd5b70d4ecc339d8be9deb20b213455bf"

["commonware_codec::types::bytes::tests::conformance::Bytes"]
n_cases = 1024
hash = "fdd4c85d5e7d598fc52a95403b81d92dd7816dd8c93d0a7330014a2e71c27e59"

["commonware_codec::types::hash_map::tests::conformance::HashMap<u32, u32>"]
n_cases = 1024
hash = "50faddad1116de4876604ce756fded13f10468fa1ab3da6dc6510cfcb5c48ff4"

["commonware_codec::types::hash_set::tests::conformance::HashSet<u32>"]
n_cases = 1024
hash = "18fd2f3e052208b254639e83e8d6cd6f8e0106dfc46b048b5bbf8128d98b430b"

["commonware_codec::types::net::test::conformance::Ipv4Addr"]
n_cases = 1024
hash = "631bdedc7971ec2e0a241cb7778417552e609f1e59c979ef42fcdc692cf3ed34"

["commonware_codec::types::net::test::conformance::Ipv6Addr"]
n_cases = 1024
hash = "334c91a0a280977f6f9804eaaa8abbd8454bc5ac8240842f33482405ea371f62"

["commonware_codec::types::net::test::conformance::SocketAddr"]
n_cases = 1024
hash = "df17643dc192ebd573579445dbfdc656e4892977e976c386a1eeb29ca573f484"

["commonware_codec::types::net::test::conformance::SocketAddrV4"]
n_cases = 1024
hash = "d8b220e0a72164fd7ab432382e2caa9b55d29936fe50e721a2ef349bd48781ab"

["commonware_codec::types::net::test::conformance::SocketAddrV6"]
n_cases = 1024
hash = "6903da75416ba669f6cacb645863dbac9ee99514f6e33c8836c0d142bc8bb8d1"

["commonware_codec::types::primitives::tests::conformance::()"]
n_cases = 1024
hash = "9f1dcbc35c350d6027f98be0f5c8b43b42ca52b7604459c0c42be3aa88913d47"

["commonware_codec::types::primitives::tests::conformance::Option<u64>"]
n_cases = 1024
hash = "ac91aab3d31a9d58d9c31f288560fb9692c1285994afd06240597b3af6bee94a"

["commonware_codec::types::primitives::tests::conformance::[u8; 32]"]
n_cases = 1024
hash = "e7b94402b6621a7345af31d64a348f1686ded896cd4eb999376d162a748f2d6f"

["commonware_codec::types::primitives::tests::conformance::bool"]
n_cases = 1024
hash = "198713cff6a8fc4143ad7d76abc9cefbc4a83da1788db166c9e27e2840d027a5"

["commonware_codec::types::primitives::tests::conformance::f32"]
n_cases = 1024
hash = "631bdedc7971ec2e0a241cb7778417552e609f1e59c979ef42fcdc692cf3ed34"

["commonware_codec::types::primitives::tests::conformance::f64"]
n_cases = 1024
hash = "0a64af25ec3432d415e1dc79a96c6e1eb1859a9babb22a843a805c819401f59d"

["commonware_codec::types::primitives::tests::conformance::i128"]
n_cases = 1024
hash = "334c91a0a280977f6f9804eaaa8abbd8454bc5ac8240842f33482405ea371f62"

["commonware_codec::types::primitives::tests::conformance::i16"]
n_cases = 1024
hash = "72a03c0af64a719dc2d631f62dd89eb3598d89e83d5b9a8d5e2063f89f4dddf9"

["commonware_codec::types::primitives::tests::conformance::i32"]
n_cases = 1024
hash = "631bdedc7971ec2e0a241cb7778417552e609f1e59c979ef42fcdc692cf3ed34"

["commonware_codec::types::primitives::tests::conformance::i64"]
n_cases = 1024
hash = "0a64af25ec3432d415e1dc79a96c6e1eb1859a9babb22a843a805c819401f59d"

["commonware_codec::types::primitives::tests::conformance::i8"]
n_cases = 1024
hash = "9d268d53456ebe649d11612abd902fe35ac0fee91ad8ffbd461699437a89d511"

["commonware_codec::types::primitives::tests::conformance::u128"]
n_cases = 1024
hash = "334c91a0a280977f6f9804eaaa8abbd8454bc5ac8240842f33482405ea371f62"

["commonware_codec::types::primitives::tests::conformance::u16"]
n_cases = 1024
hash = "72a03c0af64a719dc2d631f62dd89eb3598d89e83d5b9a8d5e2063f89f4dddf9"

["commonware_codec::types::primitives::tests::conformance::u32"]
n_cases = 1024
hash = "631bdedc7971ec2e0a241cb7778417552e609f1e59c979ef42fcdc692cf3ed34"

["commonware_codec::types::primitives::tests::conformance::u64"]
n_cases = 1024
hash = "0a64af25ec3432d415e1dc79a96c6e1eb1859a9babb22a843a805c819401f59d"

["commonware_codec::types::primitives::tests::conformance::u8"]
n_cases = 1024
hash = "9d268d53456ebe649d11612abd902fe35ac0fee91ad8ffbd461699437a89d511"

["commonware_codec::types::tuple::tests::conformance::(u32, u32)"]
n_cases = 1024
hash = "49bb8d8e9ac244f12e95b4482687ab507c9ee97391d5afdeca8fda25e602bd9b"

["commonware_codec::types::tuple::tests::conformance::(u32, u32, u32)"]
n_cases = 1024
hash = "4bebea29c2ebb927cf66d44cb6aacab3e979ca1face178bcbe5f2896f0f266f3"

["commonware_codec::types::tuple::tests::conformance::(u32, u32, u32, u32)"]
n_cases = 1024
hash = "016f7acec4791710636f82b846e87ad9b0ad89789e82c300cc0d402ecb94154b"

["commonware_codec::types::tuple::tests::conformance::(u32, u32, u32, u32, u32)"]
n_cases = 1024
hash = "f23042be1c6572852a173fdba41662241604c2c98d4d271ac787e1bd71f8f09a"

["commonware_codec::types::tuple::tests::conformance::(u32, u32, u32, u32, u32, u32)"]
n_cases = 1024
hash = "c402750ddf30a844610002a45736a43ae6b91edbfc61bad5909f6f8052525fe5"

["commonware_codec::types::vec::tests::conformance::Vec<u16>"]
n_cases = 1024
hash = "675f7187132dd4de4e68a2aebcdb6737ff54f7539571fd8ff2efe4bc56054229"

["commonware_codec::types::vec::tests::conformance::Vec<u32>"]
n_cases = 1024
hash = "06ac8dd33cb08c890be9ba3fe9b82c15badc845608587c3505cd9e6a69709d70"

["commonware_codec::types::vec::tests::conformance::Vec<u8>"]
n_cases = 1024
hash = "1331d8e7b269e960f14b2e4aa27a44bc6375ac1d00096b814a49f7a3c9cb8409"
