["commonware_codec::types::btree_map::tests::conformance::CodecConformance<BTreeMap<u32,u32>>"]
n_cases = 65536
hash = "de02f23042f3430ca8f5a062dafbaf1df38602409a760435895cdc3e0c379758"

["commonware_codec::types::btree_set::tests::conformance::CodecConformance<BTreeSet<u8>>"]
n_cases = 65536
hash = "7160fdb6ba4817a5d266a9cf9e6ff3433887aabb1c6f2b713e2befa05959ae8c"

["commonware_codec::types::bytes::tests::conformance::CodecConformance<Bytes>"]
n_cases = 65536
hash = "7f034c22d0f258e8bf599ba629b66476a608566941eace272901021013b5b72c"

["commonware_codec::types::hash_map::tests::conformance::CodecConformance<HashMap<u32,u32>>"]
n_cases = 65536
hash = "de02f23042f3430ca8f5a062dafbaf1df38602409a760435895cdc3e0c379758"

["commonware_codec::types::hash_set::tests::conformance::CodecConformance<HashSet<u32>>"]
n_cases = 65536
hash = "eefbf40005b1ebd52e422e1fb95d45ce32f789799b971ff078ff733004797aea"

["commonware_codec::types::net::test::conformance::CodecConformance<IpAddr>"]
n_cases = 65536
hash = "c8afff15840008936392131a2e0d94c6e28229e23b678ae063c3de03f1f175d9"

["commonware_codec::types::net::test::conformance::CodecConformance<Ipv4Addr>"]
n_cases = 65536
hash = "7e51d52b48539110acf575de847ef8d0c0029c877815f50b6a151db0621f2240"

["commonware_codec::types::net::test::conformance::CodecConformance<Ipv6Addr>"]
n_cases = 65536
hash = "f5456580eb69727a23bfb0281e33f467acc0c91273efebd334d3e82c9770ae76"

["commonware_codec::types::net::test::conformance::CodecConformance<SocketAddr>"]
n_cases = 65536
hash = "543fabc0899b6b2cfe167666477ef5a0f955847575778367fcf2d2772f45b38f"

["commonware_codec::types::net::test::conformance::CodecConformance<SocketAddrV4>"]
n_cases = 65536
hash = "06c31cc25b2c478ab4396e0985e9eac8141dbddb1fc5658860a74487e5141ac0"

["commonware_codec::types::net::test::conformance::CodecConformance<SocketAddrV6>"]
n_cases = 65536
hash = "dec425115852830913efdf4222b03b61a15834a3bb5e92020a952da3372642f8"

["commonware_codec::types::primitives::tests::conformance::CodecConformance<()>"]
n_cases = 65536
hash = "07854d2fef297a06ba81685e660c332de36d5d18d546927d30daad6d7fda1541"

["commonware_codec::types::primitives::tests::conformance::CodecConformance<Option<u64>>"]
n_cases = 65536
hash = "f546310e71ee290cfeb987a986a6fba208a03d59c8aae7d3f63e9f5027f87d59"

["commonware_codec::types::primitives::tests::conformance::CodecConformance<[u8;32]>"]
n_cases = 65536
hash = "c0501d4a691d1fccec7c5906e8608228569d24164150edd215838593e3b77512"

["commonware_codec::types::primitives::tests::conformance::CodecConformance<bool>"]
n_cases = 65536
hash = "c5bcd1910d08e48db3680f38884d5ba0e86836ea68edb1d4fb4aac4f9ecbd063"

["commonware_codec::types::primitives::tests::conformance::CodecConformance<f32>"]
n_cases = 65536
hash = "7e51d52b48539110acf575de847ef8d0c0029c877815f50b6a151db0621f2240"

["commonware_codec::types::primitives::tests::conformance::CodecConformance<f64>"]
n_cases = 65536
hash = "73102c8e2c269bbe2afd67158252c90a683a347e7ba623e8a1b383197c0d848a"

["commonware_codec::types::primitives::tests::conformance::CodecConformance<i128>"]
n_cases = 65536
hash = "f5456580eb69727a23bfb0281e33f467acc0c91273efebd334d3e82c9770ae76"

["commonware_codec::types::primitives::tests::conformance::CodecConformance<i16>"]
n_cases = 65536
hash = "def8d88df98f27bc054cf0d8508782bcdcdda48684a886f5115b013bae1b1bd0"

["commonware_codec::types::primitives::tests::conformance::CodecConformance<i32>"]
n_cases = 65536
hash = "7e51d52b48539110acf575de847ef8d0c0029c877815f50b6a151db0621f2240"

["commonware_codec::types::primitives::tests::conformance::CodecConformance<i64>"]
n_cases = 65536
hash = "73102c8e2c269bbe2afd67158252c90a683a347e7ba623e8a1b383197c0d848a"

["commonware_codec::types::primitives::tests::conformance::CodecConformance<i8>"]
n_cases = 65536
hash = "3f11d4610d535212b93cf8b0d3601e2685a4aacc1129ad57622d857db94db68e"

["commonware_codec::types::primitives::tests::conformance::CodecConformance<u128>"]
n_cases = 65536
hash = "f5456580eb69727a23bfb0281e33f467acc0c91273efebd334d3e82c9770ae76"

["commonware_codec::types::primitives::tests::conformance::CodecConformance<u16>"]
n_cases = 65536
hash = "def8d88df98f27bc054cf0d8508782bcdcdda48684a886f5115b013bae1b1bd0"

["commonware_codec::types::primitives::tests::conformance::CodecConformance<u32>"]
n_cases = 65536
hash = "7e51d52b48539110acf575de847ef8d0c0029c877815f50b6a151db0621f2240"

["commonware_codec::types::primitives::tests::conformance::CodecConformance<u64>"]
n_cases = 65536
hash = "73102c8e2c269bbe2afd67158252c90a683a347e7ba623e8a1b383197c0d848a"

["commonware_codec::types::primitives::tests::conformance::CodecConformance<u8>"]
n_cases = 65536
hash = "3f11d4610d535212b93cf8b0d3601e2685a4aacc1129ad57622d857db94db68e"

["commonware_codec::types::tuple::tests::conformance::CodecConformance<(u32,u32)>"]
n_cases = 65536
hash = "73102c8e2c269bbe2afd67158252c90a683a347e7ba623e8a1b383197c0d848a"

["commonware_codec::types::tuple::tests::conformance::CodecConformance<(u32,u32,u32)>"]
n_cases = 65536
hash = "074b9674e0997e724949866ca8ae5c52a15d270140c1ae82626ea6d917e089f8"

["commonware_codec::types::tuple::tests::conformance::CodecConformance<(u32,u32,u32,u32)>"]
n_cases = 65536
hash = "f5456580eb69727a23bfb0281e33f467acc0c91273efebd334d3e82c9770ae76"

["commonware_codec::types::tuple::tests::conformance::CodecConformance<(u32,u32,u32,u32,u32)>"]
n_cases = 65536
hash = "fa5e588e9074776440c9d7e46729cc60c8d0cea87e5afc4326640106abcea7ba"

["commonware_codec::types::tuple::tests::conformance::CodecConformance<(u32,u32,u32,u32,u32,u32)>"]
n_cases = 65536
hash = "457f73ee7d5f80f0d4a274509b374edddecfc881a9cbd0864691bf1a14f304a1"

["commonware_codec::types::vec::tests::conformance::CodecConformance<Vec<u16>>"]
n_cases = 65536
hash = "1d7557e1bf5e21ab93f08f66ef423be4271f8d65fa5417f3e220b2ccb8d5e101"

["commonware_codec::types::vec::tests::conformance::CodecConformance<Vec<u32>>"]
n_cases = 65536
hash = "ecd9e0e96ab4fde62a3726dc299e3569ad24c25c16853fe7c954796d64aa0388"

["commonware_codec::types::vec::tests::conformance::CodecConformance<Vec<u8>>"]
n_cases = 65536
hash = "edc22446bb2952609d0c8daccf2d22f8ad2b71eedfcf45296c3f4db49d78404a"

["commonware_codec::varint::tests::conformance::CodecConformance<SInt<i128>>"]
n_cases = 65536
hash = "42320f03747b52912d8dbb129a5958fe00ebd434a3381e3aa7daca2f48981113"

["commonware_codec::varint::tests::conformance::CodecConformance<SInt<i16>>"]
n_cases = 65536
hash = "c2e6da214e9447b09327dfe6356eb765d753c4faa5430920b01ee0dab6870514"

["commonware_codec::varint::tests::conformance::CodecConformance<SInt<i32>>"]
n_cases = 65536
hash = "24c94e3ee52cd4e9838b2e092fe328d94d6d5cee56690070f70c322849e1d2a6"

["commonware_codec::varint::tests::conformance::CodecConformance<SInt<i64>>"]
n_cases = 65536
hash = "2f24c93ed0351071f864d22d2f5782f7395569da09eabc42341807dbd5422d72"

["commonware_codec::varint::tests::conformance::CodecConformance<UInt<u128>>"]
n_cases = 65536
hash = "29b319cdfd0c760440086a14ebb5bec17e34de582d3d94f127ccb6e292b8b779"

["commonware_codec::varint::tests::conformance::CodecConformance<UInt<u16>>"]
n_cases = 65536
hash = "aa339ca7dadc09fed8de62561dfad318b44d0c43a7348d5f73dd0db286ec6658"

["commonware_codec::varint::tests::conformance::CodecConformance<UInt<u32>>"]
n_cases = 65536
hash = "f0b66ee345e9e295c50b522d9cf3501d95cd70cecfe7bfd315c970ffa78ede40"

["commonware_codec::varint::tests::conformance::CodecConformance<UInt<u64>>"]
n_cases = 65536
hash = "56ab85978136cb50f12ea89c8d25ce24451788172fe9d3d3c063f7ae6342d279"
